### ISSUE TITLE
[TASK] BMS System Implementation

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv#91]
## Description
On ASV, inside Battery packages we have BMS system who is responsible for monitoring individual battery cell Temperature, nominal voltage, current, voltage drop and so forth. It is a crucial system to get right. Vortex memebers previously tried to implement this but never finished it. We have to finish implementing the driver and then not only braod cast this data to ROS, but also save it into a .CSV file, else we get disqualified in future competitions.

Create a logger for BMS. Should run at startup of rpi

## Tasks
- [x] Look into unfinished driver code and understand what is going on. Contact "Kristian Sem", previous second in command in Vortex, as he wrote driver code
- [x] Create a prototype code that takes out data from BMS and prints it on the screen (Dont have to have perfect code at this stage)
- [x] Take BMS prototype Driver code and make a "library" that other codes, when importaed, can get all the information of both 2 battery package states. This "library" should be well writen and documented.
- [x] Create A BMS ROS interface node that uses BMS Driver "library".  Every time you launch this ROS node, it will start publishing data from both BMS'es into their own seperated topics that the rest of the ROS echosystem can use
- [x] Test the whole system in real life
- [x] DOCUMENT!!!

## Useflull links:
-  Unfinished BMS Driver: https://github.com/vortexntnu/vortex-asv/tree/feature/njord/sensors/bms
-  How to have a static USB name for BMS: https://vortex.a2hosted.com/index.php/Create_USB-device_specific_/dev/tty_connections
