### ISSUE TITLE
[TASK] PSM Sensor System

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv#93]
## Description
The ASV has a PSM. It takes Voltage and Current data going into internal electrical instruments on board. This is the same module we have on our AUV Beluga, however now we have to move the driver code to ASV repository as well. There also has to be some few name and variable changes to the driver. At the same time  we have to split code in 2 as the code has both ROS and Driver code in the same file, which is not ideal to debug and scalle further

## Todo List:
- [ ] Look at the old PSM Driver that has also ROS inside. Read up on Wiki to understand how it works.
- [ ] Make a prototype PSM Driver that does NOT include ROS, we want ROS and Driver code seperated. (Code in this stage dont have to be perfect)
- [ ] Make a full fledge PSM Driver "Library" that other code files can import and call function to get current and voltage values. Make this code clean and well documented.
- [ ] With the new PSM Driver "Library" make a new code that is a ROS node. This ROS node publishes data from PSM to the whole ROS echosystem
- [ ] Test the whole system.
- [ ] DOCUMENT!!! (This time there is some documentation, so dont have to work that hard)

## Usefull links:
- PSM Wiki page: https://vortex.a2hosted.com/index.php/PSM
- PSM Driver+ROS code: https://github.com/vortexntnu/vortex-auv/blob/development/mission/internal_status/src/battery_monitor.py
