### ISSUE TITLE
[TASK] Temperature Sensor System

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv#94]
## Description
Electrical has impelmented 6 Temperature sensors on board. The goal is to measure ambient temperature inside of the Freya ASV with 3 sensors. At the same time use other 3 sensors and attach them to points of interest that usually generate a lot of heat and monitor their behavious under operation.
Electrical has already attached all 6 sensors and conected them to a Arduino. They are analog sensor and their values are sampled by arduino and converted to real temperature data, this part electro has gracefully done for uss already. The only part we need to do is conect this Arduino to I2C and get data to RPI and then publish it to ROS.

## Todo List:
- [x] Look into the Arduino code and ask electrical if there are any questions as the whole electro contributed to the project
- [x] Make a I2C impelemntation that sends all 6 sensor data simultaniously from Arduino. Basicaly make Arduino I2C impelementation. Take inspiration from Bootleg ESC code listed under "Usefull link section"
- [x] Make a Temperature Driver prototype code on RPI side that takes data from I2C buss and prints temperature data in the correct order. Take inspiration from Bootleg ESC code listed under "Usefull link section"
- [x] Clean upp Arduino code and document it
- [x] Make Temperature Driver "Library" that other code files can use on RPI. This library should be clean and well documented.
- [x] Now that we have a Temperature Driver "Library", make a ROS node that uses this "Library" to publsih Temperature data for all the sensors.
- [x] Test the whole system out
- [ ] DOCUMENT!!!

## Usefull links:
- ARDUINO: Bootleg ESC Code to take inspiration for simultanious I2C data transfer: https://github.com/vortexntnu/vortex-asv-firmware/blob/main/bootleg_ESC/src/main.cpp
- RPI: Bootleg ESC Code to take inspiration for simultanious I2C data transfer: https://github.com/vortexntnu/vortex-asv/blob/feature/njord/motion/thruster_interface/src/thruster_interface.cpp
- Arduino Temperature Code: https://github.com/vortexntnu/vortex-asv-firmware/tree/19-add-temperature-measurements-to-freya/telemetry-sensing/telemetry-sensing

**Comment by PizzaAllTheWay** [comment]
The 6 Temperature sensors are cheap simple analog NTC Termistor. Basicallly when temperature goes upp, its resistence drop exponentially, so it is a non linear curve which means you have to calibrate code to convert exponential curves

**Comment by PizzaAllTheWay** [comment]
Needs documenting

**Comment by PizzaAllTheWay** [comment]
Finished in 4h, speedrun ez gg clap
